version: '3.8'
services:
  light-web:
    hostname: light-web
    build:
      context: ./light-website
      dockerfile: Dockerfile.prod
    expose:
      - "3000"
    networks:
      - app_network
    depends_on:
      - light-api
    env_file:
      - ./light-website/.env.production

  light-api:
    hostname: light-api
    build:
      context: ./light-core
      dockerfile: Dockerfile.prod
    expose:
      - "5002"
    networks:
      - app_network
    # security_opt:
    #   - no-new-privileges:true
    # cap_drop:
    #   - ALL
    # cap_add:
    #   - NET_BIND_SERVICE
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/health"]  # Adjust as needed
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:latest
    ports:
      - "80:80"   # HTTP traffic (handled by root domain's SSL)
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf   # Nginx config
    networks:
      - app_network   # Single network for internal and external communication
    depends_on:
      - light-web
      - light-api

networks:
  app_network:
    driver: bridge
