# This docker-compose file:
# - creates the next app image/container
# - create the flask app image/container
# - exposes the nextjs app (frontend or website)
# - allows the nextjs app to communicate with flask app only using internal docker network

version: '3.8'
services:
  light-web:
    hostname: light-web
    build:
      context: ./light-website
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    networks:
      - internal_network
    depends_on:
      - light-api
    env_file:
      - ./light-website/.env.production # Specify the path to the env file

  light-api:
    hostname: light-api
    build:
      context: ./light-core
      dockerfile: Dockerfile.prod
    networks:
      - internal_network
    ports:
      - "5002:5002" 
networks:
  internal_network:
    driver: bridge
